# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('dtNascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], default='C', max_length=1, verbose_name='Estado civil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True, verbose_name='Endereço')),
                ('nrEndereco', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nº endereço')),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('cidade', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', localflavor.br.models.BRStateField(default='RS', max_length=2)),
                ('nrTelCelular', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('nrTelFixo', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo')),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60, verbose_name='Descrição')),
                ('ean', models.CharField(max_length=13, verbose_name='EAN')),
                ('precoCusto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço custo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('estoqueAtual', models.IntegerField(default=1, verbose_name='Estoque atual')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdSolicitada', models.IntegerField(default=1, verbose_name='Quantidade solicitada')),
                ('qtdDevolvida', models.IntegerField(default=1, verbose_name='Quantidade devolvida')),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço unitário')),
                ('vlrDescontoUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor desconto unitário')),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjPedido.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtAbertura', models.DateField(auto_now_add=True, verbose_name='Data da abertura')),
                ('dtFechamento', models.DateField(verbose_name='Data do fechamento')),
                ('ativo', models.BooleanField(default=True)),
                ('informacoes', models.TextField(blank=True, null=True, verbose_name='Informações')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Comissão')),
                ('idColaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjPedido.Colaborador', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name_plural': 'Supervisores',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Comissão')),
                ('idColaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjPedido.Colaborador', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='idSupervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjPedido.Supervisor', verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjPedido.Vendedor', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='idPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjPedido.Pedido'),
        ),
    ]
