# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjPedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='precoUnitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='qtdDevolvida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade devolvida'),
        ),
    ]
