# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjPedido', '0004_auto_20171110_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensdevolucao',
            name='itenspedido_ptr',
        ),
        migrations.DeleteModel(
            name='ItensDevolucao',
        ),
    ]
