# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjPedido', '0005_auto_20171110_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensDevolucao',
            fields=[
                ('itenspedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DjPedido.ItensPedido')),
            ],
            bases=('DjPedido.itenspedido',),
        ),
    ]
